### ISSUE TITLE
Question about roles directory names

### ISSUE THREAD

**Issue by h2non** [codingbunch/ansible-nexus-oss#1]
According to the documentation, the repository should be cloned in the global Ansible roles directory or in a custom `roles/` repository under `nexus` name as directory. 

However, in the playbook configuration, in the `roles` field it's defined as name `ansible-nexus`.
As far I know, the role identifier should match with the role directory name, since Ansible try to discover it looking in various `roles` directories by this name identifier.

The question is: is this correct? Instead of declare this:

``` yaml
- name: Nexus
  hosts: nexus
  roles:
    - ansible-nexus
```

Should I declare this?

``` yaml
- name: Nexus
  hosts: nexus
  roles:
    - nexus
```
